### ISSUE TITLE
Would be great if we create something similar to laradock 

### ISSUE THREAD

**Issue by ydatech** [yiisoft/yii2-docker#1]
I have something similar base on laradock https://github.com/ydatech/yii2-laradock.  but there are some configuration that we don't need for yii2..

**Comment by mikehaertl** [comment]
@ydatech We will focus on a very minimal image here, see https://github.com/yiisoft/yii2/issues/13722. So your project could extend from the base image here. But we will not add extra functionality, at least not for now.

**Comment by ydatech** [comment]
@mikehaertl Okay then, I'll be waiting.
