### ISSUE TITLE
acceptance tests

### ISSUE THREAD

**Issue by masihfathi** [yiisoft/yii2-docker#101]
hi 
how is it possible to run acceptance tests with yii2 docker image?

**Comment by schmunk42** [comment]
Sure. But you also need a Selenium container.

See https://github.com/dmstr/phd5-app for an example setup.

**Comment by masihfathi** [comment]
excuse me would you please help me.
i configured selenium but when i run tests inside a container i got this error:
  [Facebook\WebDriver\Exception\UnknownErrorException] unknown error: net::ERR_CONNECTION_CLOSED
  (Session info: chrome=85.0.4183.83)  

and in the app log i got this error:
app_1         | [Fri Oct  2 21:08:53 2020] 172.31.0.2:37898 Invalid request (Unsupported SSL request)
app_1         | [Fri Oct  2 21:08:53 2020] 172.31.0.2:37900 Invalid request (Unsupported SSL request)
app_1         | [Fri Oct  2 21:08:53 2020] 172.31.0.2:37902 Invalid request (Unsupported SSL request)
app_1         | [Fri Oct  2 21:08:53 2020] 172.31.0.2:37904 Invalid request (Unsupported SSL request)
app_1         | [Fri Oct  2 21:08:53 2020] 172.31.0.2:37906 Invalid request (Unsupported SSL request)
app_1         | [Fri Oct  2 21:08:53 2020] 172.31.0.2:37908 Invalid request (Unsupported SSL request)
app_1         | [Fri Oct  2 21:08:53 2020] 172.31.0.2:37910 Invalid request (Unsupported SSL request)
app_1         | [Fri Oct  2 21:08:53 2020] 172.31.0.2:37912 Invalid request (Unsupported SSL request)
app_1         | [Fri Oct  2 21:08:53 2020] 172.31.0.2:37914 Invalid request (Unsupported SSL request)

my acceptance.suite.yml config:
        - WebDriver:
            url: http://app:8001
            browser: chrome
            host: webdriver
            port: 4444
and docker-compose.yml
  webdriver:
    image: selenium/standalone-chrome
    restart: always
    hostname: webdriver
    privileged: true
    shm_size: 2g
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
#      # Mount shm, see https://github.com/SeleniumHQ/docker-selenium#running-the-images
      - /dev/shm:/dev/shm
    networks:
      - yii

**Comment by schmunk42** [comment]
I think you should ask the question about the SSL error over here: https://github.com/SeleniumHQ/docker-selenium or try not to use SSL to debug.

**Comment by masihfathi** [comment]
Thanks. finally solved the problem.
https://forum.yiiframework.com/t/acceptance-tests-failed-in-docker-container/130649

**Comment by schmunk42** [comment]
app is reserved by the browser? 

Am 3. Oktober 2020 20:30:24 MESZ schrieb masih fathi <notifications@github.com>:
>Thanks. finally solved the problem.
>https://forum.yiiframework.com/t/acceptance-tests-failed-in-docker-container/130649
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/yiisoft/yii2-docker/issues/101#issuecomment-703145613

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by masihfathi** [comment]
> app is reserved by the browser? Am 3. Oktober 2020 20:30:24 MESZ schrieb masih fathi <notifications@github.com>:
> […](#)
> Thanks. finally solved the problem. https://forum.yiiframework.com/t/acceptance-tests-failed-in-docker-container/130649 -- You are receiving this because you modified the open/close state. Reply to this email directly or view it on GitHub: [#101 (comment)](https://github.com/yiisoft/yii2-docker/issues/101#issuecomment-703145613)
> -- Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

yes it is reserved by browser
