### ISSUE TITLE
Migrate to GitHub actions

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-docker#106]
See https://github.com/yiisoft/yii2-docker/issues/104

**Comment by odai-alali** [comment]
In the draft I've created, the tests runs successfully on all php version which is not the case on Travis 🤔

The ci runs on ubuntu-latest which already include docker, so there is no need to install it.

What is `TRAVIS_TAG` in [before_script](https://github.com/yiisoft/yii2-docker/blob/master/.travis.yml#L30-L40) section? I am not really understanding what's happenning there

**Comment by samdark** [comment]
@schmunk42 you know the thing way better than I am. Would you please check it?

**Comment by schmunk42** [comment]
> What is TRAVIS_TAG in before_script section? I am not really understanding what's happenning there

That determines if we are on a tag, and we build a tagged docker image like `7.4-2020-11-1`, see https://github.com/yiisoft/yii2-docker/blob/master/.travis.yml#L34

**Comment by samdark** [comment]
That's git tag, right? It should be available via `${GITHUB_REF:10}`

**Comment by schmunk42** [comment]
> That's git tag, right? It should be available via `${GITHUB_REF:10}`

Yes. We don't use semver here.
