### ISSUE TITLE
xdebug 3.0 invalid default config - no debug possible

### ISSUE THREAD

**Issue by airmoi** [yiisoft/yii2-docker#113]
Hi,

Looks like the last image use an invalid xdebug config (at least for php 7.3-apache).
Many options have been renamed in v3, but its still v2 option defined in .ini

Most important things are : 
* missing xdebug.mode=debug
* missing xdebug.client_host (replaces remote_host)
* missing xdebug.client_port  (replaces remote_port) : new default value is 9003 so perhaps this one can be ignored now

**Comment by herzog-dev** [comment]
@samdark @airmoi Does this still work for 2.x versions?

**Comment by samdark** [comment]
Well, old images were build with old config so I think they should work as before. @schmunk42 am I right?

**Comment by schmunk42** [comment]
Looks like the images are wokring, comment was from me with another account.
Tried with 7.1 fpm
