### ISSUE TITLE
add parametrized composer version

### ISSUE THREAD

**Issue by Insolita** [yiisoft/yii2-docker#116]
Allow composer 2.x version by env/arg

**Comment by Insolita** [comment]
May add pr

**Comment by schmunk42** [comment]
Since fxp asset-plugin is not compatible with v2 yet I'd wait until https://github.com/fxpio/composer-asset-plugin/issues/334 is ready.

I'd then switch completely to v2, instead of builiding another 3-4 images.

**Comment by Insolita** [comment]
That issue not solved for more than half of the year, and I'm not sure that anybody works on this. As a fact composer-asset-plugin mostly required for old yii versions only. The newest ones work perfectly with asset-packagist.org So, for 2.x we can skip its installation (and hirak/prestissimo too)

**Comment by schmunk42** [comment]
@Insolita Could you try adding 

```
RUN composer self-update
```

to your `Dockerfile` and see if things are working OK for you?

We, for example, are still using fxp/asset-plugin for most of our projects, because in many of our projects we run into memory issues with asset-packagist (depends on the packages you use).

**Comment by Insolita** [comment]
I also remove "hirak/prestissimo"  before update composer version. It works well.

Do you think about the switch to https://github.com/fxpio/foxy with https://github.com/krissss/foxy-yii2-convert ?

**Comment by schmunk42** [comment]
> I also remove "hirak/prestissimo" before update composer version. It works well.

Yes, no longer needed, parallelization is built in composer v2.

**Comment by anasjaghoub** [comment]
I fixed it by adding 
`RUN composer self-update --2` to the Dockerfile

**Comment by schmunk42** [comment]
We have composer 2 since a while.
