### ISSUE TITLE
short_open_tag = On and doesn't work

### ISSUE THREAD

**Issue by borysenko** [yiisoft/yii2-docker#120]
I am using 7.1-apache. In the base.ini file change short_open_tag = 0 to short_open_tag = On and doesn't work

**Comment by schmunk42** [comment]
Did you rebuild the image and restarted the container?
Did you try `short_open_tag=1`?

**Comment by marcovtwout** [comment]
short_open_tag was deprecated in 7.4 and removed in 8.0, this issue can be closed.

**Comment by mtangoo** [comment]
Since no response since Feb 2021, am closing this. @borysenko, feel free to reopen it if it is still an issue!
