### ISSUE TITLE
Missing support for the new GitHub OAuth tokens

### ISSUE THREAD

**Issue by golubev** [yiisoft/yii2-docker#125]
Hi! I got a new GH token string that looks like "ghp_xxxx" (while my old GH token is simply a hex string) and ran into the same issue as described here -https://github.com/composer/composer/issues/8314#issuecomment-811756365

```
  [UnexpectedValueException]                                                                                      
  Your github oauth token for github.com contains invalid characters: "ghp_xxxxxxxx"  
```

Composer release `1.10.21` fixes this issue - https://github.com/composer/composer/releases/tag/1.10.21

**Comment by schmunk42** [comment]
fixed in PR

**Comment by Elma0314** [comment]
Many thanks, could you give some details for updateting composer in Magento 2.  For example, where should I put this conposer files to in the following link that you recommended. 

https://github.com/composer/composer/releases/tag/1.10.21

**Comment by schmunk42** [comment]
@Elma0314 You should ask this question in a Magento Forum I think.

**Comment by golubev** [comment]
Hello @Elma0314. Sorry, but I'm not familiar with Magento at all.
