### ISSUE TITLE
PHP 8 builds are failing (headers have already been sent)

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2-docker#128]
See https://github.com/yiisoft/yii2-docker/runs/2458125469?check_suite_focus=true

@bizley @samdark Any idea why? They were running fine locally.

**Comment by bizley** [comment]
I will run it on my machine and get back to you.

**Comment by bizley** [comment]
I've got exactly the same failed result. Investigating now.

**Comment by bizley** [comment]
[This line](https://github.com/yiisoft/yii2/blob/master/tests/framework/di/ContainerTest.php#L218) throws deprecation error and causes an output being printed thus ending in the error message.
I think it's not caught in Yii because of error levels set. I will prepare fix.

**Comment by schmunk42** [comment]
Works now, PHP 8 images are available on DockerHub.
