### ISSUE TITLE
Will docker-yii2 Support arm devices?

### ISSUE THREAD

**Issue by yawaweb** [yiisoft/yii2-docker#129]
Hello,
Does docker-yii2 plan to support arm devices like Raspberry Pi ?

**Comment by schmunk42** [comment]
What must be done to support it? Isn't it more like you need to build on the required platform?

**Comment by rzakirov** [comment]
There is a problem with performance in Apple M1 (high cpu usage), because it emulates x64. 

![image](https://user-images.githubusercontent.com/4517950/124556803-68f41800-de41-11eb-817d-af76913f8b11.png)

**Comment by schmunk42** [comment]
Is it this? https://docs.docker.com/desktop/multi-arch/#build-multi-arch-images-with-buildx

I have no experience with it, PRs welcome. (should not blow up image-size)

**Comment by dsx90** [comment]
Я решил данную проблему взяв исходник https://github.com/yiisoft/yii2-docker/blob/master/php/Dockerfile-debian
и в docker-compose добавил:
build:
      context: ../../..
      dockerfile: docker/build/local/backend/Dockerfile-debian
      args:
        - PHP_BASE_IMAGE_VERSION=7.4.28-fpm

**Comment by yepes** [comment]
> Я решил данную проблему взяв исходник https://github.com/yiisoft/yii2-docker/blob/master/php/Dockerfile-debian
> и в docker-compose добавил:
> build:
> dockerfile: Dockerfile-debian
> args:
> - PHP_BASE_IMAGE_VERSION=7.4.28-fpm

can you please post your docker-compose.yml for reference?
