### ISSUE TITLE
Composer Error `Your github oauth token for github.com contains invalid characters`

### ISSUE THREAD

**Issue by Alex-DA** [yiisoft/yii2-docker#136]
Hello, it seems that GitHub changed the format of their auth tokens and this break with our current composer version.

We need to upgrade to composer >= 2.0.12 at https://github.com/yiisoft/yii2-docker/blob/c29f89e9f57876c1f4cdc935a762d5e11a9147de/php/Dockerfile-debian#L47

More info:

* https://nono.ma/github-oauth-token-for-github-com-contains-invalid-characters-on-composer-install
* https://stackoverflow.com/questions/26691681/composer-unexpectedvalueexception-error-will-trying-to-use-composer-to-install

**Comment by samdark** [comment]
@Alex-DA do you have time for a pull request?

**Comment by Alex-DA** [comment]
Hello @samdark , this is my first PR https://github.com/yiisoft/yii2-docker/pull/137 

Also I saw it this other things:

1. MacOS comment on Readme
`If you are using macOS, you can fill xdebug.remote_host with host.docker.internal, due to a network limitation on mac`
but if you check the configuration file of xdebug is already using `host.docker.internal`

https://github.com/yiisoft/yii2-docker/blob/c29f89e9f57876c1f4cdc935a762d5e11a9147de/php/image-files/usr/local/etc/php/conf.d/xdebug.ini#L6

Can I delete that comment in the same PR?

2. ENV var about Prestissimo

https://github.com/yiisoft/yii2-docker/blob/c29f89e9f57876c1f4cdc935a762d5e11a9147de/php/Dockerfile-debian#L35

But the prestissimo is not needed anymore on composer 2... `This plugin is for Composer1; Composer2 is very fast on its own. Uninstall this plugin and update the Composer itself.`
+info https://github.com/hirak/prestissimo

Can I delete that line in the same PR?

**Comment by samdark** [comment]
> Can I delete that comment in the same PR?
> Can I delete that line in the same PR?

Yes.

**Comment by Alex-DA** [comment]
Ok, done.

**Comment by samdark** [comment]
Merged. Thanks. Images should be automatically prepared by GitHub actions currently running.
