### ISSUE TITLE
manifest unknown

### ISSUE THREAD

**Issue by royemosby** [yiisoft/yii2-docker#141]
running `docker pull yiisoftware/yii2-php` gives me `Error response from daemon: manifest for yiisoftware/yii-php:latest not found: manifest unknown: manifest unknown`

MacOS 11.6
Docker version 20.10.8, build 3967b7d

**Comment by schmunk42** [comment]
Yes, there is no `latest` image, pick one here: https://github.com/yiisoft/yii2-docker#available-versions-for-yiisoftwareyii2-php
