### ISSUE TITLE
Add MsSQL extensions

### ISSUE THREAD

**Issue by ruudboon** [yiisoft/yii2-docker#142]
Would it be possible to add the MsSql extension to the default images?

**Comment by schmunk42** [comment]
Don't think it really possible, since it's support is very limited, see https://github.com/mlocati/docker-php-extension-installer

And AFAIR it's also quite large.

But for 5.5 / 5.6 you should be able to install it by:
```
RUN install-php-extensions \
        mssql \
```

**Comment by ruudboon** [comment]
Should not be that hard for 7 or 8 (https://www.microsoft.com/en-us/sql-server/developer-get-started/php/ubuntu). I does create extra overhead, maybe we could add step to the https://github.com/yiisoft/yii2-docker/blob/master/docs/install-extensions.md ?

**Comment by schmunk42** [comment]
>  maybe we could add steps to the https://github.com/yiisoft/yii2-docker/blob/master/docs/install-extensions.md ?

sure, PR for docs welcome

Or you create a PR at mlocati's repo.
