### ISSUE TITLE
8.1 pipeline fails

### ISSUE THREAD

**Issue by Isitar** [yiisoft/yii2-docker#146]
there is no 8.1 image available since the pipeline fails.

i tried updateing the TEST_YII_VERSION but the tests failed anyway..

**Comment by bizley** [comment]
Is it possible that phpunit patch fails for 8.1 here?

**Comment by schmunk42** [comment]
Is is possibly related to https://github.com/yiisoft/yii2-docker/runs/5345420194?check_suite_focus=true#step:7:223 ?

```
For additional security you should declare the allow-plugins config with a list of packages names that are allowed to run code. See https://getcomposer.org/allow-plugins
```

**Comment by bizley** [comment]
Hmm, way ahead of scheduled date but possibly. It's worth to check though since the configuration is easy and will not affect negatively anything.

**Comment by samdark** [comment]
Is it solved now?

**Comment by Isitar** [comment]
yes, the pipeline runs :)
