### ISSUE TITLE
Install unzip command

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2-docker#149]
Composer shows the following warning on `composer install` or `composer update`.

> As there is no 'unzip' nor '7z' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' or '7z' may remediate them.

![image](https://user-images.githubusercontent.com/189796/168636091-15c63c91-6e41-43a9-b1aa-b24fde583d22.png)

`unzip` should be installed on the image by default to avoid this.

**Comment by cebe** [comment]
https://gist.github.com/cebe/f55ab1d85db2a548a1119b947f71b2fa

```
git clone git@gist.github.com:f55ab1d85db2a548a1119b947f71b2fa.git test
cd test
docker-compose up -d
docker-compose exec web composer install
```

![image](https://user-images.githubusercontent.com/189796/168823607-b3860b2c-f5a8-43e1-8024-862d3a9e4006.png)

**Comment by schmunk42** [comment]
fixed in https://github.com/yiisoft/yii2-docker/commit/5b71c2d16c5624eb2444a0e20e7f75469e2ee5bd
