### ISSUE TITLE
Build failed - compose file invalid - unsupported option target

### ISSUE THREAD

**Issue by yavro** [yiisoft/yii2-docker#150]
Hello, I am stuck at building this image. After `cp .env-dist .env` I ran `docker-compose build` but got an error:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.php-min.build contains unsupported option: 'target'
services.php-dev.build contains unsupported option: 'target'
```

After some searching I have found that there is an issue with target option in compose files version https://github.com/docker/compose/issues/5714
But in my case changing version in the compose files only produces another error:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.php-dev: 'extends'
```

Docker compose info:

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by schmunk42** [comment]
I think you need to upgrade docker-compose itself

Am 20. Mai 2022 16:27:36 MESZ schrieb yavro ***@***.***>:
>Hello, I am stuck at building this image. After `cp .env-dist .env` I ran `docker-compose build` but got an error:
>`
>ERROR: The Compose file './docker-compose.yml' is invalid because:
>services.php-min.build contains unsupported option: 'target'
>services.php-dev.build contains unsupported option: 'target'
>`
>After some searching I found there is an issue with target option in compose files version https://github.com/docker/compose/issues/5714
>But in my case changing version in the compose files only produces another error:
>`ERROR: The Compose file './docker-compose.yml' is invalid because:
>Unsupported config option for services.php-dev: 'extends'
>`
>
>Docker compose info:
>`docker-compose version 1.25.0, build unknown
>docker-py version: 4.1.0
>CPython version: 3.8.10
>OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
>`
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/yiisoft/yii2-docker/issues/150
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by yavro** [comment]
Oh, I did not realize that I had docker-compose installed from ubuntu repo. I removed the old version and manually installed the latest version from github and now everything works. Sorry for opening unnecessary issue.
