### ISSUE TITLE
PDOException: could not find driver (trying to use mysql)

### ISSUE THREAD

**Issue by gvanto** [yiisoft/yii2-docker#157]
in my Dockerfile I have:

I have googled and come across what I thought might help (but hasn't):
https://stackoverflow.com/questions/44603941/how-to-enable-pdo-mysql-in-the-php-docker-image

https://stackoverflow.com/questions/49521272/php-docker-pdo-mysql-driver-not-found

```
# Install system packages
RUN apt-get update && \
    apt-get -y install \
            git \
            unzip \
        --no-install-recommends && \
    apt-get clean && \
    docker-php-ext-install mysqli pdo pdo_mysql && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install common system packages for PHP extensions recommended for Yii 2.0 Framework
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions \
    soap \
    zip \
    bcmath \
    exif \
    gd \
    opcache \
    #pdo \
    #pdo_mysql \
    # mysqli \
    pdo_pgsql \
    imagick
#        mongodb${PECL_MONGODB_INSTALL_SUFFIX} \
#        xdebug${PECL_XDEBUG_INSTALL_SUFFIX}

# https://stackoverflow.com/questions/44603941/how-to-enable-pdo-mysql-in-the-php-docker-image
RUN docker-php-ext-enable mysqli pdo_mysql
```

When I log into container (it runs OK), and do a php -m command, I see pdo_mysql is not in list of modules ...

File permissions:
![image](https://user-images.githubusercontent.com/8372918/221537138-35c4be2c-91c9-4a18-a0d5-da96f6df96b8.png)

My base.ini (as per this git repo):

```
; Required timezone
date.timezone = UTC

; General settings
memory_limit=128M
max_execution_time=30
sys_temp_dir=/tmp
upload_max_filesize=512M
upload_tmp_dir=/tmp
post_max_size=512M

; Security, Debug & Logs
expose_php=off
cgi.fix_pathinfo=0
log_errors=on
error_reporting=E_ALL
html_errors=on
xdebug.default_enable=off

; Opcache
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
;opcache.validate_timestamps=off
opcache.fast_shutdown=0
opcache.enable_cli=1

; PHP language options
short_open_tag=0

; Doesn't work:
; https://stackoverflow.com/questions/49521272/php-docker-pdo-mysql-driver-not-found
;extension=pdo.so
;extension=pdo_mysql.so
;extension=pdo_sqlite.so
;extension=mysql.so
```

Something is stopping these pdo (and pdo_mysql) modules from either being installed/being enabled I'm not sure how to determine which / how to fix it ...

Any help much appreciated, fairly new at docker images!

**Comment by schmunk42** [comment]
> Something is stopping these pdo (and pdo_mysql) modules from either being installed/being enabled I'm not sure how to determine which / how to fix it ...

You have them commented...

```
    #pdo \
    #pdo_mysql \
    # mysqli \
```

**Comment by gvanto** [comment]
hi @schmunk42 yes they are commented there because it wasn't working (uncommented), so I added them to line above (which still isn't working):

![image](https://user-images.githubusercontent.com/8372918/221921779-b3f3af74-6a0d-47de-9849-d572cd871d3d.png)

**Comment by schmunk42** [comment]
> because it wasn't working (uncommented)

Which error did you get?

**Comment by gvanto** [comment]
hey @schmunk42 

Error I got:
 PDOException: could not find driver

**Comment by schmunk42** [comment]
And you have built your Docker image **with** those lines?

```
RUN install-php-extensions \
    pdo \
    pdo_mysql \
```

They are available on the built images:

```
> docker run --rm yiisoftware/yii2-php:8.0-fpm php -i | grep -i pdo
Configure Command =>  './configure'  '--build=x86_64-linux-gnu' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--with-mhash' '--with-pic' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-password-argon2' '--with-sodium=shared' '--with-pdo-sqlite=/usr' '--with-sqlite3=/usr' '--with-curl' '--with-iconv' '--with-openssl' '--with-readline' '--with-zlib' '--disable-phpdbg' '--with-pear' '--with-libdir=lib/x86_64-linux-gnu' '--disable-cgi' '--enable-fpm' '--with-fpm-user=www-data' '--with-fpm-group=www-data' 'build_alias=x86_64-linux-gnu'
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini,
API Extensions => pdo_mysql
PDO
PDO support => enabled
PDO drivers => sqlite, mysql, pgsql
pdo_mysql
PDO Driver for MySQL => enabled
pdo_mysql.default_socket => no value => no value
pdo_pgsql
PDO Driver for PostgreSQL => enabled
pdo_sqlite
PDO Driver for SQLite 3.x => enabled
```

Maybe there's a typo in your db config?

**Comment by schmunk42** [comment]
PS: Forget `docker-php-ext-install` use `install-php-extensions` from `mlocati/php-extension-installer` it takes care about correctly installing and enabling extensions.

**Comment by gvanto** [comment]
ok thanks let me dig a bit and get back to you, appreciate the help

**Comment by gvanto** [comment]
docker-compose up output (container runs fine, but getting the pdo error above when trying to access site):

![image](https://user-images.githubusercontent.com/8372918/221932244-b9605c57-7ee4-4b0c-8a6a-01aaa9a66d2a.png)

**Comment by gvanto** [comment]
> And you have built your Docker image **with** those lines?
> 
> ```
> RUN install-php-extensions \
>     pdo \
>     pdo_mysql \
> ```
> 
> They are available on the built images:
> 
> ```
> > docker run --rm yiisoftware/yii2-php:8.0-fpm php -i | grep -i pdo
> Configure Command =>  './configure'  '--build=x86_64-linux-gnu' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--with-mhash' '--with-pic' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-password-argon2' '--with-sodium=shared' '--with-pdo-sqlite=/usr' '--with-sqlite3=/usr' '--with-curl' '--with-iconv' '--with-openssl' '--with-readline' '--with-zlib' '--disable-phpdbg' '--with-pear' '--with-libdir=lib/x86_64-linux-gnu' '--disable-cgi' '--enable-fpm' '--with-fpm-user=www-data' '--with-fpm-group=www-data' 'build_alias=x86_64-linux-gnu'
> /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
> /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini,
> API Extensions => pdo_mysql
> PDO
> PDO support => enabled
> PDO drivers => sqlite, mysql, pgsql
> pdo_mysql
> PDO Driver for MySQL => enabled
> pdo_mysql.default_socket => no value => no value
> pdo_pgsql
> PDO Driver for PostgreSQL => enabled
> pdo_sqlite
> PDO Driver for SQLite 3.x => enabled
> ```
> 
> Maybe there's a typo in your db config?

Which db config are you referring to @schmunk42  ?

**Comment by schmunk42** [comment]
> Only file here is base.ini:

Other `ini` files are added with the install command. Use `php -i` to see what's loaded or go into the config dir in the container.

> Which db config are you referring to @schmunk42 ?

Your app config, when you use ie. `mysqli` instead of `mysql` you get the same error "driver not found"

```
            'dsn' => 'mysqli:host=db;port=3306;dbname=phd5'
```

Out of curiosity: Why are you completely rebuilding the images, instead of using the ones from Docker Hub as base images?

**Comment by gvanto** [comment]
hey @schmunk42 thanks for infos ...

OK I thought mysqli was something mysql needed, turns out its something different so I'm leaving it out.

so I tried uncommenting pdo_mysql line in base.ini:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/8372918/222741021-65a43e61-4e18-4849-b4c7-9464af2dc1f3.png">

But then get: (at least it seems to be trying to load something pdo related!)

![image](https://user-images.githubusercontent.com/8372918/222740335-bb2f7411-dd57-45d1-a588-ec36d380181d.png)

> Out of curiosity: Why are you completely rebuilding the images, instead of using the ones from Docker Hub as base images?

Well to be honest to have more control over what's happening and also because I need php7.4 (php7.2 really, but 7.4 seems to be closest thing still supported).

**Comment by gvanto** [comment]
Oh shucks just saw that mysql not supported for php7.4 here:
https://github.com/mlocati/docker-php-extension-installer#supported-php-extensions

Looks like I will need to install it some other way (docker-php-ext-install)

**Comment by gvanto** [comment]
> Other ini files are added with the install command. Use php -i to see what's loaded or go into the config dir in the container.

which install command? 

I am running:
```
# Install common system packages for PHP extensions recommended for Yii 2.0 Framework
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions \
    soap \
    zip \
    bcmath \
    exif \
    gd \
    opcache \
    pdo_mysql \
    imagick
```

But not seeing (expected) file:
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini

**Comment by schmunk42** [comment]
Min image:
```
> docker-compose run --rm php-min ls  /usr/local/etc/php/conf.d/
Creating yii2fpmnginx_php-min_run ... done
Switching uid for 'www-data' to 33
usermod: no changes
base.ini  docker-fpm.ini  docker-php-ext-intl.ini  docker-php-ext-sodium.ini
```

Dev image:
```
> docker-compose run --rm php-dev ls  /usr/local/etc/php/conf.d/
Creating yii2fpmnginx_php-dev_run ... done
Switching uid for 'www-data' to 33
usermod: no changes
base.ini                    docker-php-ext-opcache.ini
docker-fpm.ini              docker-php-ext-pcntl.ini
docker-php-ext-bcmath.ini   docker-php-ext-pdo_mysql.ini
docker-php-ext-exif.ini     docker-php-ext-pdo_pgsql.ini
docker-php-ext-gd.ini       docker-php-ext-soap.ini
docker-php-ext-imagick.ini  docker-php-ext-sodium.ini
docker-php-ext-intl.ini     docker-php-ext-zip.ini
docker-php-ext-mongodb.ini  xdebug.ini
```

I am closing this, since it's not an issue with these images to my understanding.

**Comment by gvanto** [comment]
Got it working with 
`FROM yiisoftware/yii2-php:7.4-fpm AS min`

So yeh not a problem with yii2 images (and thus not for this forum, but maybe a different one, still don't understand why it doesn't work with "FROM php:7.4-fpm AS min" and using the correct install commands but whatever, this works for now :) )

thanks for the help @schmunk42 appreciated!
