### ISSUE TITLE
Usage of this docker with existing yii2 project?

### ISSUE THREAD

**Issue by dadinugroho** [yiisoft/yii2-docker#159]
I have an existing yii2 project, providing Backend Services to an angular Frontend. Is that possible to use this yii2-docker to run my existing project? I am thinking of creating a parent folder or put my project folder inside this yii2-docker. 

I am new to docker, can anyone help with some guidance to do this?

My reason to use this yii2-docker is the integration of XDEBUG and if I am correct, I can use this docker on production level as well?

Thank you in advance.

**Comment by dadinugroho** [comment]
Thank you @samdark is there any guidance on how can I make the project accessible from the docker?

**Comment by samdark** [comment]
- https://docs.docker.com/get-started/overview/
- https://docker-curriculum.com/

**Comment by dadinugroho** [comment]
Thank you @samdark
