### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by linuxanton-2469** [yiisoft/yii2-docker#167]
In php/image-files/dev/usr/local/bin/composer use the following shebang line:

#!/usr/bin/env -S bash

Otherwise the installation will break.

**Comment by schmunk42** [comment]
Which error do you get?

**Comment by linuxanton-2469** [comment]
Hi Schmunk,

/usr/bin/env \rbash not found

Habe mittlerweile herausgefunden, dass es an der automatischen Konvertierung von git liegt. 

Lösung:
git config --global core.autocrlf input
git rm --cached -r .
git reset --hard


For repo owners and contributors

If you own a repo or contribute to it, set mandatory LF line endings for .sh files right in the repo by adding the .gitattributes file with the following line:

*.sh text eol=lf

Grüße aus Günzburg
Anton
