### ISSUE TITLE
iMap missing and won't install

### ISSUE THREAD

**Issue by fiSCIENCES** [yiisoft/yii2-docker#173]
Hi,

How can I add imap to my backend Docker image from Yii2 Advanced Project Template.
I have tried: `apt-get install php-imap` (should get php8.3-imap).
But I'm getting:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package php-imap is a virtual package provided by:
  php8.2-imap 8.2.24-1~deb12u1 [Not candidate version]
E: Package 'php-imap' has no installation candidate
```
Even: ```
apt-get update && apt-get install -y \
    libicu-dev libonig-dev libzip-dev \
    && docker-php-ext-install imap
```
Compiled everything but get stuck at the "Installing shared.extensions: " (never end and I need to do CTRL-C to end it).
```
Build complete.
Don't forget to run 'make test'.

+ strip --strip-all modules/imap.so
Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20230831/
```
Thank you.

**Comment by schmunk42** [comment]
Tryinstall-php-extensions imapVon meinem iPhone gesendetAm 17.11.2024 um 09:46 schrieb Martin Pineault ***@***.***>:﻿
Hi,
How can I add imap to my backend Docker image from Yii2 Advanced Project Template.
I have tried: apt-get install php-imap
But I'm getting:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package php-imap is a virtual package provided by:
  php8.2-imap 8.2.24-1~deb12u1 [Not candidate version]
E: Package 'php-imap' has no installation candidate

Even: ```
apt-get update && apt-get install -y 
libicu-dev libonig-dev libzip-dev 
&& docker-php-ext-install imap
Compiled everything but get stuck at the "Installing shared.extensions: " (never end and I need to do CTRL-C to end it).

Build complete.
Don't forget to run 'make test'.

strip --strip-all modules/imap.so
Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20230831/

Thank you.

**Comment by fiSCIENCES** [comment]
Won't work, after 10 minutes, nothing happen (had to do CTRL-C again):
```
# install-php-extensions
install-php-extensions v.2.6.1
#StandWithUkraine

^C
#
```

**Comment by fiSCIENCES** [comment]
New information, tried on another machine:
```
# install-php-extensions
install-php-extensions v.2.2.19
#StandWithUkraine
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9005 (through xdebug.client_host/xdebug.client_port).

```
Then I started PhpStorm so it's connected to xdebug:
```
# install-php-extensions
install-php-extensions v.2.2.19
#StandWithUkraine
```
And then it hang forever!

**Comment by schmunk42** [comment]
Formatting seems tricky on my phone….TryRUN install-php-extensions imapIn DockerfileVon meinem iPhone gesendetAm 17.11.2024 um 11:38 schrieb Martin Pineault ***@***.***>:﻿
New information, tried on another machine:
# install-php-extensions
install-php-extensions v.2.2.19
#StandWithUkraine
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9005 (through xdebug.client_host/xdebug.client_port).


Then I started PhpStorm so it's connected to xdebug:
# install-php-extensions
install-php-extensions v.2.2.19
#StandWithUkraine

And then it hang forever!

**Comment by schmunk42** [comment]
Sorry all line breaks get removed somehow?!

**Comment by fiSCIENCES** [comment]
I was aware of the stripped CR/LF problem.
OK, rebuild of Yii2 images for Docker redone.
iMap now installed and working.
Thank you!
