### ISSUE TITLE
Any chance for cent/red hat based containers?

### ISSUE THREAD

**Issue by davidjeddy** [yiisoft/yii2-docker#2]
Any chance for container Dockerfile's based on REHL / other than Debian?

**Comment by samdark** [comment]
@davidjeddy what are benefits?

**Comment by mikehaertl** [comment]
@davidjeddy For now our plan is to extend our images from the official PHP docker images. They have a guaranteed stability and provide an easy way to add more extensions. 

Using other distros would make us responsible for the PHP part, too. I think, that's out of the scope of this little project. If you need something like this you'd be better off building your own base image. Our images will be very minimalstic anyway - so building something similar for other Linux should be quite easy.

**Comment by schmunk42** [comment]
We could consider this later on, in a contrib section. 

I.e. building mssql drivers is almost impossible on Debian or Alpine.
I am working on a build system at the moment which could be scaled to handle this (sometime :))

WIP: https://gitlab.com/yiisoft/yii2-docker/pipelines/6904679

**Comment by davidjeddy** [comment]
Why build drivers for the SQL services? Provide the Yii2 docker image with two or three overrides that would load MySQL / MariaDB / MsSQL / Postgres. The framework should not care what the DB tech is. Setup php-fpm on the framework's image to return the parsed code and be done.

**Comment by schmunk42** [comment]
> Side note: Why build drivers for the SQL services?

@davidjeddy How would you use MSSQL or Cubrid with PDO? There might be several others...

I had to use some really exotic base-images, these are also candidates for a contrib or experimental section:
- https://github.com/yiisoft/yii2/tree/master/tests/mssql
- https://github.com/yiisoft/yii2/tree/master/tests/cubrid

**Comment by davidjeddy** [comment]
@schmunk42 Ah, that is what you meant. Ignore mny prev. comment about data sources; my misunderstanding.
