### ISSUE TITLE
Internal versioning of yiiframework/yii2-php

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2-docker#20]
Currently there's no versioning of these images, since they are "just" versioned like the PHP base-image.

Basically the `yii2-php` images "only" install a set of extensions and won't require much versioning - but you never know. Instead of appending a `1.0`, `1.1` suffix, we could also add a string like `20171113` which reflects the image "API" at a certain point of time, ie. available ENV variables. Usually the images should be upgradeable without breaking (but you never know).

@yiisoft/core-developers

**Comment by samdark** [comment]
Yes, it's good to add some versioning.

**Comment by cebe** [comment]
the main thing they provide is PHP. so they should contain the PHP version, we may append something if we have multiple versions of ours for the same PHP version.

**Comment by schmunk42** [comment]
Any preferences?
- `7.1-apache-1.0`
- `7.1-apache-v1`
- `7.1-apache-20171114.0`
- `7.1-apache-17.11.0`

I'd tend to the last one...

**Comment by samdark** [comment]
Last one is good.

**Comment by schmunk42** [comment]
Fixed, first tagged image ist `*-17.12.0`, see also https://hub.docker.com/r/yiisoftware/yii2-php/tags/
