### ISSUE TITLE
Install hirak/prestissimo on the base-images?

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2-docker#21]
Pros:
 - the plugin https://github.com/hirak/prestissimo speeds up built time by factor ~5.
 - very stable (actually never had an issue with it)

Cons:
 - it's an additional plugin

@yiisoft/core-developers

**Comment by samdark** [comment]
It's fine to use it. I've tried it and it is, indeed, quite stable.

**Comment by dynasource** [comment]
is it usefull enough for projects with few dependencies?

**Comment by samdark** [comment]
It is.

**Comment by schmunk42** [comment]
@dynasource The main thing it does is, it parallelizes package downloads. It does not hook into the solver or does any big magic.

**Comment by dynasource** [comment]
I know. I've tried (and benchmarked) it twice and both times I concluded it not to have any value in case of frequent installs of projects with little dependencies. 

When you install regularly, composer dependencies will already be cached resulting into extra overhead of prestissimo.

**Comment by schmunk42** [comment]
Since Docker build-steps are completely isolated tasks, you can not cache anything here. Parallelizing downloads is the best optimization I've seen so far.

And for sure, it does not help you at all when using git repositories.

**Comment by dynasource** [comment]
alright. Im convinced.
