### ISSUE TITLE
checkdnsrr() always returns true in alpine images

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2-docker#24]
The issue described here: https://github.com/docker-library/php/issues/442

Leads to:

```
1) yiiunit\framework\validators\EmailValidatorTest::testValidateValueMx
Failed asserting that true is false.

/yii2/tests/framework/validators/EmailValidatorTest.php:120
/yii2/vendor/phpunit/phpunit/phpunit:52
```

So the `EMailValidator` can not be used with `checkDNS` on Alpine.

How should we handle that?
- do still not build Alpine images 😞 
- mention it in the docs and skip test
- throw an Exception when using the checkDNS setting on Alpine

**Comment by samdark** [comment]
Providing official image where a part of the framework doesn't work doesn't make sense to me.

**Comment by schmunk42** [comment]
> Providing official image where a part of the framework doesn't work doesn't make sense to me.

Yeah, I absolutely agree. Official images will be Debian-only, see also #25.

Additional note: We also had numerous highly esoteric issues with Alpine, ie. segfaults when using `wkhtml2pdf`, but also weird permission issues in nginx tmp files.

Giving that amount of issues, it might take a while to mature for Alpine, maybe it's worth to look at it again in 2022 😸  Most of these issues seem strongly related to **not using glibc**, but **musl**.
