### ISSUE TITLE
Alpine: NumberValidator test with comma-locale fails

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2-docker#25]
Looks like there are some more **intl** issues: https://github.com/docker-library/php/issues/219

Failed test:

```
2) yiiunit\framework\validators\NumberValidatorTest::testValidateValueSimple
Failed asserting that false is true.

/yii2/tests/framework/validators/NumberValidatorTest.php:85
/yii2/vendor/phpunit/phpunit/phpunit:52
```

Test-source:
```
$this->setCommaDecimalLocale();
$this->assertTrue($val->validate('25,45'));
$this->restoreLocale();
```

Can someone shed some more light on this?

**Comment by samdark** [comment]
That test depends on particular system locale (where comma is used as decimal separator) to present in the OS. Seems in this case it's not there.

**Comment by schmunk42** [comment]
Doesn't even work with this fix: https://github.com/voidlinux/void-mklive/pull/48 (which needs minutes to apply btw.)
Also related: https://github.com/gliderlabs/docker-alpine/issues/144#issuecomment-339906345

Given this an https://github.com/yiisoft/yii2-docker/issues/24 - it looks like there'll be no official PHP Alpine images until those issues are fixed in upstream.
