### ISSUE TITLE
Mod_rewrite in apache flavor

### ISSUE THREAD

**Issue by gugatxr** [yiisoft/yii2-docker#31]
Hi, 
I create a app using the  7.1-apache version and the image don't have do mod_rewrite enabled.
We activate by default?

Thanks

**Comment by dersonsena** [comment]
I had to activate on the hand too! I think it would be quite useful to come with the rewrite module enabled.

Thank you!

**Comment by schmunk42** [comment]
I think we can enable rewrite in the `Dockerfile`.
@cebe, @samdark Do you also think it should be a default?

In the meantime add this to your projects `Dockerfile`:

```
RUN a2enmod rewrite 
```

**Comment by dersonsena** [comment]
I made it here locally to work @samdark @cebe. In my opinion this should come enabled. There will hardly be web applications that do not need this.

**Comment by gugatxr** [comment]
I am doing in this way that you said @schmunk42.

**Comment by samdark** [comment]
Yes, having it on by default is fine.

**Comment by schmunk42** [comment]
fixed in #33
