### ISSUE TITLE
Error response from daemon: manifest for yiisoftware/yii2-php:latest not found

### ISSUE THREAD

**Issue by bologer** [yiisoft/yii2-docker#37]
Trying to get the image via: 

```
docker pull yiisoftware/yii2-php
```

and getting the following error: 

```
Using default tag: latest
Error response from daemon: manifest for yiisoftware/yii2-php:latest not found
```

I was searching for this problem but did not find anything. Some issue on GitHub was having some discussing regarding `docker login`, but I registered on hub and logged in from local environment and tried to get the image and still having the same error. 

## Docker info 
```
docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

And then 

```
docker search yiisoftware
NAME                   DESCRIPTION                               STARS     OFFICIAL   AUTOMATED
yiisoftware/yii2-php   Official Docker images suitable for Yii   7  
```

Which does not make any sense. 

Any clue?

**Comment by schmunk42** [comment]
We're not building `latest` images atm, you need to pick one of these:

```
7.2-apache
7.1-apache
7.0-apache
5.6-apache
7.1-fpm
7.2-fpm
7.0-fpm
5.6-fpm
```

**Comment by bologer** [comment]
@schmunk42 what about nginx?

**Comment by rustamwin** [comment]
@bologer  `fpm` images are set to nginx

**Comment by bologer** [comment]
@rustamwin so if I install `yiisoftware/yii2-php:7.1-fpm` I should be having nginx preinstalled as well?

**Comment by schmunk42** [comment]
See https://github.com/yiisoft/yii2-docker/issues/12#issuecomment-393107745

**Comment by schmunk42** [comment]
Closing in favor of #12
