### ISSUE TITLE
Api tests on Yii2 docker image - apache2 server is not running

### ISSUE THREAD

**Issue by kaspirovski** [yiisoft/yii2-docker#51]
Hello. I have problem with Yii2 application running on `yiisoftware/yii2-php:7.1-apache`. When i try to run codeception api tests with command `docker-compose run --rm php codecept run api --coverage`, i need apache2 server running, but its not and i get error: `file_get_contents(http://localhost/index-test.php/c3/report/clear): failed to open stream: Cannot assign requested address`. I think its caused by overwriting command (from documentation of  `docker-compose run`: `the command passed by run overrides the command defined in the service configuration.`). Is it possible that given command to run tests overrides command to run apache2 server? Has anyone had similar problem?

@UPDATE
When i first up container with `docker-compose up php` and then run command `docker-compose exec php codecept run api --coverage` it works fine.

**Comment by schmunk42** [comment]
You need to run `docker-compose up -d` to start your application stack.

Then

    docker-compose exec php codecept run api --coverage

to execute something in the running container.
