### ISSUE TITLE
Error when I run the command docker pull yiisoftware/yii2-php

### ISSUE THREAD

**Issue by calcio** [yiisoft/yii2-docker#52]
Hi everyone.

I'm trying run the command **docker pull yiisoftware/yii2-php** from **https://hub.docker.com/r/yiisoftware/yii2-php/**, but I get this error: 
```
Using default tag: latest
Error response from daemon: manifest for yiisoftware/yii2-php:latest not found
```

**Comment by rustamwin** [comment]
Duplicates #37

**Comment by rustamwin** [comment]
See [tags](https://hub.docker.com/r/yiisoftware/yii2-php/tags)

**Comment by schmunk42** [comment]
Closing this, since there's no `latest` image - also there's no really good candidate for `latest` at the moment I think. If someone has a different opinion, please let us know.
