### ISSUE TITLE
Deprecate 5.6 and 7.0 images

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2-docker#60]
PHP 5.6 and 7.0 reach their EOL in less than one month.
http://php.net/supported-versions.php

Also because of this issue https://github.com/yiisoft/yii2-docker/issues/58 currently we're currently not building updated 5.6 images, see https://hub.docker.com/r/yiisoftware/yii2-php/tags/

How should we deprecate those images?
- remove the `5.6-...` tags, so users would have to go to the latest tagged version, eg. `5.6-fpm-17.12.0` if they still need PHP 5.6
- or just keep things at is, which can be tricky for a user to find out that an image was not built recently

**Comment by samdark** [comment]
Is there a way to keep legacy containers but mark them as deprecated?

**Comment by schmunk42** [comment]
Not an official one, I even don't know about a widely used convention.

E.g. you can still `docker pull php:5.5` which gives you a 2 years old image.
PHP 5.5 is just not listed anymore here: https://hub.docker.com/_/php/

We could also "rename" (create a new and delete) the tag to `5.6-fpm-EOL`.

**Comment by samdark** [comment]
https://github.com/docker/hub-feedback/issues/907 yeah...

**Comment by schmunk42** [comment]
I think I won't rename anything, it's just how images are used to 99%. So closing...

PS: Should we create images named `yii-php` for 3.0 and up?

**Comment by samdark** [comment]
Yes.
