### ISSUE TITLE
Bug with build argument

### ISSUE THREAD

**Issue by sss-CRS-sss** [yiisoft/yii2-docker#62]
i copied env and exec build, but get next error:
```
Building php
Step 1/15 : ARG PHP_BASE_IMAGE_VERSION
ERROR: Service 'php' failed to build: Please provide a source image with `from` prior to commit
```
PS: ubuntu 16.04.5 LTS 
Docker version 17.03.2-ce, build f5ec1e2
docker-compose version 1.8.0, build unknown

**Comment by schmunk42** [comment]
Please update `docker-compose`.
