### ISSUE TITLE
oci8 pdo_oci plans?

### ISSUE THREAD

**Issue by Isitar** [yiisoft/yii2-docker#63]
Is there a plan to add oci8 / pdo_oci support?

i added it in my docker image (before this one was available) like this:

```RUN alien -i /opt/oracle/oracle-instantclient18.3-basic-18.3.0.0.0-1.x86_64.rpm
RUN alien -i /opt/oracle/oracle-instantclient18.3-devel-18.3.0.0.0-1.x86_64.rpm

ENV LD_LIBRARY_PATH=/usr/lib/oracle/18.3/client64/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
RUN echo "/usr/lib/oracle/18.3/client64/lib/" > /etc/ld.so.conf.d/oracle.conf && chmod o+r /etc/ld.so.conf.d/oracle.conf
ENV ORACLE_HOME=/usr/lib/oracle/18.3/client64
ENV C_INCLUDE_PATH=/usr/include/oracle/18.3/client64/
RUN  ln -s /usr/include/oracle/18.3/client64 $ORACLE_HOME/include

RUN docker-php-ext-install pdo oci8 pdo_oci

RUN rm -rf /opt/oracle
```

but it is a real hassle to do it this way since i need to include the oracle-instantclient in my source repository

**Comment by schmunk42** [comment]
I'd add this to https://github.com/yiisoft/yii2-docker/blob/master/docs/install-extensions.md

Can you create a PR?

PS: The `RUN` commands should be combined into one, otherwise `rm` won't reduce the total image size and the data is still in a layer.

**Comment by Isitar** [comment]
I guess you think about something like this:

### pdo_oci
#### Debian

    #install pdo_oci
    ENV LD_LIBRARY_PATH=/usr/lib/oracle/18.3/client64/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    ENV ORACLE_HOME=/usr/lib/oracle/18.3/client64
    ENV C_INCLUDE_PATH=/usr/include/oracle/18.3/client64/
    RUN alien -i /opt/oracle/oracle-instantclient18.3-devel-18.3.0.0.0-1.x86_64.rpm && \
        echo "/usr/lib/oracle/18.3/client64/lib/" > /etc/ld.so.conf.d/oracle.conf && \
        chmod o+r /etc/ld.so.conf.d/oracle.conf && \
        ln -s /usr/include/oracle/18.3/client64 $ORACLE_HOME/include && \
        docker-php-ext-install pdo oci8 pdo_oci && \
        rm -rf /opt/oracle

in my example you need to copy the data to the container, i do it with these commands: 

    RUN mkdir /opt/oracle
    COPY oracle_instant_client/ /opt/oracle

I guess then the total image size will remain large.
I'm no docker expert and don't know if there is any better way.

**Comment by Isitar** [comment]
> > in my example you need to copy the data to the container,
> 
> You mean the data in the database?

no, the oracle-instantclient18.3-devel-18.3.0.0.0-1.x86_64.rpm

**Comment by schmunk42** [comment]
I see. How big is it?
I have no experience in installing oracle. Things can always be optimized ... :)

**Comment by Isitar** [comment]
all in all it's 54 MB.
When I look at others solution, they pull it form their github repo (https://github.com/caffeinalab/php-fpm-oci8/blob/master/Dockerfile) to avoid huge image sizes

**Comment by schmunk42** [comment]
How about downloading the `rpm` with curl, convert and install it and clean and remove afterwards; all in one `RUN` command?

**Comment by Isitar** [comment]
It's typical oracle stuff, I didn't find a way to download it directly without registering and all that stuff.
You can download it here: https://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html
