### ISSUE TITLE
Composer permission

### ISSUE THREAD

**Issue by issidorov** [yiisoft/yii2-docker#66]
Hi.
Composer not executing for www-data user.
Error:
```
www-data@2cae7b4c925c:/app$ composer install
bash: /usr/local/bin/composer: Permission denied
```

**Comment by schmunk42** [comment]
I think the `www-data` user should not be able to execute `composer`, you need to do that as `root` in the container, which is the actual default in Docker context.

**Comment by pigochu** [comment]
I modify /usr/local/bin/composer to 755  manually , and in docker-compose volumes map ~/.composer:/var/www/.compose
I can run it on WSL2.
Is there any reason why composer's permissions cannot be preset to default 755?

**Comment by schmunk42** [comment]
Actually, in Docker context, we run composer as root in the container.
Which user are you in the Docker container on WSL? `whoami`

**Comment by pigochu** [comment]
I use docker for development yii2 app, and use vs code ide,so sometimes must edit composer.json or remove assert. The UID is 1000

**Comment by schmunk42** [comment]
Can you specify the user in your compose file?

`user: 1` in service definition

**Comment by schmunk42** [comment]
And, when using Docker you should run `composer` always IN the container. Otherwise you might mess things up. (Different PHP version, ....)

**Comment by pigochu** [comment]
@schmunk42 

> Can you specify the user in your compose file?
> 
> `user: 1` in service definition
What do you mean ? I can't understand


> And, when using Docker you should run `composer` always IN the container. Otherwise you might mess things up. (Different PHP version, ....)
I always run composer in container , but my command is `docker-compose exec -u www-data ...` , because I remap volume ~/.composer:/var/www/.compose . and I don't want when  composer  install, it will change my folder permission to root.

**Comment by schmunk42** [comment]
Like so: https://stackoverflow.com/a/48730146/291573

To become root in the container.

**Comment by pigochu** [comment]
> Like so: https://stackoverflow.com/a/48730146/291573
> 
> To become root in the container.

But vs code IDE on Wsl2 run as UID 1000 .so I can not write or delete some file or folders

**Comment by schmunk42** [comment]
fixed in https://github.com/yiisoft/yii2-docker/commit/a7ebe787bee6310ba411d69d9c2cdaa7e6fdc920
