### ISSUE TITLE
Don't see the the variable `PHP_ENABLE_XDEBUG` in use.

### ISSUE THREAD

**Issue by simmonHuong** [yiisoft/yii2-docker#70]
```
# Check if Xdebug extension need to be compiled
RUN cd /tmp && \
    git clone git://github.com/xdebug/xdebug.git && \
    cd xdebug && \
    git checkout 2.7.0beta1 && \
    phpize && \
    ./configure --enable-xdebug && \
    make && \
    make install && \
    rm -rf /tmp/xdebug

# Environment settings
ENV PHP_USER_ID=33 \
    PHP_ENABLE_XDEBUG=0 \
    PATH=/app:/app/vendor/bin:/root/.composer/vendor/bin:$PATH \
    TERM=linux \
    VERSION_PRESTISSIMO_PLUGIN=^0.3.7 \
COMPOSER_ALLOW_SUPERUSER=1

```
If I am get it right,this code block do two things:
1. Install Xdebug
2. Define environment variables

You can't control whether Xdebug will be installing or not by `PHP_ENABLE_XDEBUG`.

**Comment by schmunk42** [comment]
It's used in the entry script: https://github.com/yiisoft/yii2-docker/blob/master/php/image-files/usr/local/bin/docker-php-entrypoint#L9-L13

Xdebug is always installed but not loaded/enabled by default, the second block just defines defaults, yes.
