### ISSUE TITLE
How to run composer install in DockerFile

### ISSUE THREAD

**Issue by agsachdev** [yiisoft/yii2-docker#71]
Need a help for composer 

Please explain how run composer install or update 

got a error

Composer could not find a composer.json file in /app/web
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

i add code in my dockerfile

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#Install/update Vandor 
RUN composer install

**Comment by schmunk42** [comment]
You need to copy `composer.json` and `composer.lock` onto the image and then run the installation

```
COPY ./composer.* /app/
RUN composer install --no-dev --prefer-dist --optimize-autoloader && \
         composer clear-cache
```

It is recommended to copy the rest of your applications source afterwards, to avoid rebuilding for every code change.
