### ISSUE TITLE
Broken [7.3-fpm-alpine3.10] build

### ISSUE THREAD

**Issue by rafaelmiti** [yiisoft/yii2-docker#77]
```
## PHP-fpm & nginx
COMPOSE_PROJECT_NAME=yii2fpm
COMPOSE_FILE=docker-compose.yml:docker-compose.fpm-nginx.yml
DOCKERFILE_FLAVOUR=alpine
PHP_BASE_IMAGE_VERSION=7.3-fpm-alpine3.10
```

With the above .env i got:

```
checking for libzip... not found
configure: error: Please reinstall the libzip distribution
ERROR: Service 'php' failed to build: The command '/bin/sh -c apk --update --virtual build-deps add [...] returned a non-zero code: 1
```

**Comment by schmunk42** [comment]
Just added the info to FAQ: https://github.com/yiisoft/yii2-docker/blob/master/README.md#faq

**Comment by rafaelmiti** [comment]
> Just added the info to FAQ: https://github.com/yiisoft/yii2-docker/blob/master/README.md#faq

It would be nice to change the ".env-dist" file to remove the alpine references?

**Comment by schmunk42** [comment]
fixed in https://github.com/yiisoft/yii2-docker/commit/46575169fbc35dcab3c2dfb0fb980adf1a295df8
