### ISSUE TITLE
Automatic update of images when php/pgsql/mysql are updated

### ISSUE THREAD

**Issue by kmindi** [yiisoft/yii2-docker#80]
Apparently, the yii2-docker images are out of date in comparison to the php images. (e.g. right now 7.3-apache is based on debian buster whereas it was based on debian stretch when the images were last built...this includes missing security updates to the used apache) 

In Docker Hub it is possible to enable triggers for the build depending on updates in other docker repositories. This should be enabled for the used dependencies. https://docs.docker.com/docker-hub/builds/

**Comment by samdark** [comment]
@schmunk42 ?

**Comment by schmunk42** [comment]
@kmindi You could double-check `latest` again, there was an issue with pushing from Travis.

Since we build **and test** images on Travis, auto-update triggers from Docker-Hub can't be used.

**Comment by kmindi** [comment]
Okay, and travis is only triggered manually, wich also includes manual pushes to this repo?

If yes, there is also an option in travis to create regular/scheduled builds: https://docs.travis-ci.com/user/cron-jobs/

I have not looked at your condiguration, but I guess for latest a daily build, and for still maintained images a weekly build would be good, or maybe more than latest daily, and only others with a longer interval. Is that possible?

**Comment by schmunk42** [comment]
I've just enabled daily builds for `latest`.

We usually do manual (date-)tags like `19.7.0` from time to time.

**Comment by kmindi** [comment]
Like this it is not fixed.

I don't think this is secure then (which does not align with Yii) because the other images will get outdated quickly, only `latest` will be up to date, but at the same time might introduce new backwards incompatible changes.
The other images should stay fairly stable even with regular rebuilds, depending on the choice of php docker images tag. They offer varuous debian versions which are known for stability, if that is of concern here.

**Comment by schmunk42** [comment]
What is missing in your opinion? We should be changed?

We build from `7.x-fpm` and `7.x-apache`, we support 7.1 to 7.3. `latest` is like `dev-master` it's not stable.

**Comment by kmindi** [comment]
I mean automatic daily or weekly builds are also needed for `7.x-apache` and `7.x-fpm` (not only for `latest`). If they (php or their automatic triggered build by dependencies) update a minor php version or apache version gets updated in debian, these updates should be available in yii2-docker as well, and not only from time to time, especially regarding security fixes.

**Comment by schmunk42** [comment]
Sorry for the confusion, we actually have no `latest` image. But `7.1-apache`, `7.1-fpm`, ... those are build daily now, like "latest". 

Images like `7.2-fpm-18.12.0` won't change.
