### ISSUE TITLE
How to use PHP-FPM image

### ISSUE THREAD

**Issue by icecold21** [yiisoft/yii2-docker#83]
I would like to use this image with PHP-FPM 5.x. Is there any documentation on how to write the dockerfile?

**Comment by schmunk42** [comment]
For reference (external nginx container)

- https://github.com/yiisoft/yii2-docker/blob/master/docker-compose.fpm-nginx.yml
- https://github.com/phundament/docker-images/tree/master/phundament/nginx-one/1.9

(nginx with supervisord)

- https://github.com/dmstr/docker-php-yii2/tree/release/6.x/nginx

Would be nice to have it a separate docs here.
