### ISSUE TITLE
Load PHP memcached extension

### ISSUE THREAD

**Issue by santiago33** [yiisoft/yii2-docker#85]
Invalid Configuration – yii\base\InvalidConfigException
MemCache requires PHP memcached extension to be loaded.

yii2-php:7.2-apache

**Comment by santiago33** [comment]
# Memcached
RUN apt-get -y install libz-dev libmemcached-dev libmemcached11 libmemcachedutil2 build-essential \
    && pecl install memcached \
    && echo extension=memcached.so >> /usr/local/etc/php/conf.d/memcached.ini \
    && apt-get remove -y build-essential libmemcached-dev libz-dev \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /tmp/pear

```

**Comment by yii2backendwebdeveloper** [comment]
What about for windows ?

**Comment by schmunk42** [comment]
> What about for windows ?

How does that differ when using Docker?

**Comment by yii2backendwebdeveloper** [comment]
Not using docker

**Comment by schmunk42** [comment]
This repo is about docker, please ask your question here https://forum.yiiframework.com/
