### ISSUE TITLE
Using advanced application

### ISSUE THREAD

**Issue by cluwong** [yiisoft/yii2-docker#86]
Using php-fpm & nginx setup.
I'm trying to setup using advance template, but the example provided is for basic application template. How can you config the docker file so that it goes to both frontend and backend app?
If I want to setup hostname to frontend and backend apps instead of accessing by ports, are there any options in the setup that allows this or which files should be edited to make this work?

**Comment by schmunk42** [comment]
I'd recommend using https://github.com/jwilder/nginx-proxy ie. in conjunction with http://xip.io/
