### ISSUE TITLE
configure: error: unrecognized options: --with-freetype, --with-jpeg

### ISSUE THREAD

**Issue by ichbindermann** [yiisoft/yii2-docker#87]
---> Running in 12f205492b73
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
configure: error: unrecognized options: --with-freetype, --with-jpeg
ERROR: Service 'php' failed to build: The command '/bin/sh -c if [ $X_LEGACY_GD_LIB = 1 ]; then         docker-php-ext-configure gd                 --with-freetype-dir=/usr/include/                 --with-png-dir=/usr/include/                 --with-jpeg-dir=/usr/include/;     else         docker-php-ext-configure gd                 --with-freetype=/usr/include/                 --with-jpeg=/usr/include/;     fi &&     docker-php-ext-configure bcmath &&     docker-php-ext-install         soap         zip         curl         bcmath         exif         gd         iconv         intl         mbstring         opcache         pdo_mysql         pdo_pgsql' returned a non-zero code: 1

**Comment by schmunk42** [comment]
What are your values for?
- PHP_BASE_IMAGE_VERSION
- DOCKERFILE_FLAVOUR
- X_LEGACY_GD_LIB

see also https://github.com/yiisoft/yii2-docker/blob/master/.travis.yml#L4

**Comment by Rafinol** [comment]
I added -dir prefix

50 and 51 line 
--with-freetype-dir=/usr/include/ \
--with-jpeg-dir=/usr/include/; \

in Dockerfile-debian file

**Comment by schmunk42** [comment]
@Rafinol You should set `X_LEGACY_GD_LIB=1` when building images from older Debian versions.
