### ISSUE TITLE
configure: error

### ISSUE THREAD

**Issue by sidorenkoda** [yiisoft/yii2-docker#88]
dmitry@MacBook-Pro-Dmitrij docker %  docker-compose -f docker-compose.yml up -d
WARNING: The GITHUB_API_TOKEN variable is not set. Defaulting to a blank string.
Building php
Step 1/16 : ARG PHP_BASE_IMAGE_VERSION
Step 2/16 : FROM php:${PHP_BASE_IMAGE_VERSION}
 ---> 8359fe14a60f
Step 3/16 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 316e873442a2
Step 4/16 : RUN apt-get update &&     apt-get -y install         gnupg2 &&     apt-key update &&     apt-get update &&     apt-get -y install             g++             git             curl             imagemagick             libcurl3-dev             libicu-dev             libfreetype6-dev             libjpeg-dev             libjpeg62-turbo-dev             libonig-dev             libmagickwand-dev             libpq-dev             libpng-dev             libxml2-dev             libzip-dev             zlib1g-dev             default-mysql-client             openssh-client             nano             unzip             libcurl4-openssl-dev             libssl-dev         --no-install-recommends &&         apt-get clean &&         rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Using cache
 ---> 7dd36912a59c
Step 5/16 : ARG X_LEGACY_GD_LIB=0
 ---> Using cache
 ---> 011b1a6409b0
Step 6/16 : RUN if [ $X_LEGACY_GD_LIB = 1 ]; then         docker-php-ext-configure gd                 --with-freetype-dir=/usr/include/                 --with-png-dir=/usr/include/                 --with-jpeg-dir=/usr/include/;     else         docker-php-ext-configure gd                 --with-freetype=/usr/include/                 --with-jpeg=/usr/include/;     fi &&     docker-php-ext-configure bcmath &&     docker-php-ext-install         soap         zip         curl         bcmath         exif         gd         iconv         intl         mbstring         opcache         pdo_mysql         pdo_pgsql
 ---> Running in e394c0a77a84
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
configure: error: unrecognized options: --with-freetype, --with-jpeg
**ERROR: Service 'php' failed to build: The command '/bin/sh -c if [ $X_LEGACY_GD_LIB = 1 ]; then         docker-php-ext-configure gd                 --with-freetype-dir=/usr/include/                 --with-png-dir=/usr/include/                 --with-jpeg-dir=/usr/include/;**     else         docker-php-ext-configure gd                 --with-freetype=/usr/include/                 --with-jpeg=/usr/include/;     fi &&     docker-php-ext-configure bcmath &&     docker-php-ext-install         soap         zip         curl         bcmath         exif         gd         iconv         intl         mbstring         opcache         pdo_mysql         pdo_pgsql' returned a non-zero code: 1
dmitry@MacBook-Pro-Dmitrij docker %

**Comment by schmunk42** [comment]
I have update the README https://github.com/yiisoft/yii2-docker#faq and `.env` https://github.com/yiisoft/yii2-docker/blob/master/.env-dist#L21-L22

Usually official Docker PHP images <=7.3 are build from an older Debian version, which needs other compile flags. This may change in the future.
