### ISSUE TITLE
Review Stacker

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-docker#9]
Just came over https://github.com/Maxlab/stacker. Looks similar to what we're going to do.

**Comment by mikehaertl** [comment]
From a cursory look I'd say, their goal differs a bit. Our focus is to provide minimal, universal building blocks, whereas they try to provide a full dev environment with many features. For sure that's fine for many, but it's not everyone's taste.

So I think our images still make much sense.

**Comment by samdark** [comment]
Yes. Goal is different but the project has a few cool tricks.

**Comment by schmunk42** [comment]
> Goal is different but the project has a few cool tricks.

@samdark Like which?

**Comment by samdark** [comment]
zsh usage and Yii2 autocomplete bash script.

**Comment by mikehaertl** [comment]
@samdark We could consider to "borrow" this for our `-full` flavour. If we really create one, see #7.
