### ISSUE TITLE
Error response from daemon: manifest for yiisoftware/yii2-php:latest not found

### ISSUE THREAD

**Issue by firecentaur** [yiisoft/yii2-docker#90]
Hi there, I am trying to do a docker pull using
docker pull yiisoft//yii2-docker

but get an error message: 
Using default tag: latest
Error response from daemon: manifest for yiisoftware/yii2-php:latest not found

What command do I use to pull this docker?

**Comment by schmunk42** [comment]
https://github.com/yiisoft/yii2-docker/blob/master/README.md#available-versions-for-yiisoftwareyii2-php

You need to pick a version from those above. 


Am 9. Juni 2020 23:57:15 MESZ schrieb Paul Preibisch <notifications@github.com>:
>Hi there, I am trying to do a docker pull using
>docker pull yiisoft//yii2-docker
>
>but get an error message: 
>Using default tag: latest
>Error response from daemon: manifest for yiisoftware/yii2-php:latest
>not found
>
>What command do I use to pull this docker?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/yiisoft/yii2-docker/issues/90

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
