### ISSUE TITLE
The Xdebug installed is the master branch (v3.0.0-dev) and not the latest stable (v2.9.6)

### ISSUE THREAD

**Issue by Sarke** [yiisoft/yii2-docker#96]
The Xdebug installed is the master branch (v3.0.0-dev) and not the latest stable (v2.9.6).  Is this correct?

To replicate:
`docker run --rm --env PHP_ENABLE_XDEBUG=1 yiisoftware/yii2-php:7.4-apache php -r 'echo phpversion("xdebug");'`

I noticed it because I was no longer able to connect to the remote debugger anymore.  Using the latest stable fixed the problem.

Also, why not install it using pecl?  `pecl install xdebug`

**Comment by samdark** [comment]
Pecl should be better option, I think.

**Comment by basyan** [comment]
and I can't change the xdebug version because the env variable is `VERSION_XDEBUG`, but below in dockerfile `git checkout ${XDEBUG_VERSION}`
