### ISSUE TITLE
 Service 'php' failed to build

### ISSUE THREAD

**Issue by hle-aashish** [yiisoft/yii2-docker#97]
I am new to Yii2. As mentioned in the **README**, I cloned the repo and made a copy of **.env**. But, when I do `docker-compose build` as mentioned in the readme, I am getting the following message.

```
Service 'php' failed to build: Get https://registry-1.docker.io/v2/library/php/manifests/7.4-apache: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fphp%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io: no such host
```
Anyone to help? Please.

**Comment by Sarke** [comment]
Looks like a network issue maybe?

But you don't have to build it, you can just use the built version on https://hub.docker.com/r/yiisoftware/yii2-php

**Comment by schmunk42** [comment]
It's a network problem on your side.
